
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java_ci_with_maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  docker_build_and_push:
       runs-on: ubuntu-latest
       needs: ["java_ci_with_maven"]
       steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Login to Docker Registry
         uses: docker/login-action@v1
         with:
           registry: https://cvizard.com:5001
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

       - name: Build and push
         uses: docker/build-push-action@v2
         with:
           context: .
           push: true
           tags: cvizard.com:5001/pdfconverter:${{ github.sha }}
           
  deploy:
      runs-on: ubuntu-latest
      needs: ["docker_build_and_push"]
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

     
          
#       - name: Set up SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/cvizard_ed25519
#           chmod 600 ~/.ssh/cvizard_ed25519
#           ssh-keyscan -t ed25519 ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        
      - name: install ssh
        run: sudo apt-get install -y ssh
        
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: https://cvizard.com:5001
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login cvizard.com:5001 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sed -i 's|cvizard.com:5001/pdfconverter:.*|cvizard.com:5001/pdfconverter:${{ github.sha }}|' CVizard/docker-compose.yml
            cd CVizard && docker compose stop pdfconverter && docker compose build pdfconverter && docker compose up -d pdfconverter

          
#       - name: Update Docker Compose file
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sed -i 's|cvizard.com:5001/pdfconverter:.*|cvizard.com:5001/pdfconverter:${{ github.sha }}|' CVizard/docker-compose.yml"

#       - name: Start services
#         run: |
#           ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /CVizard && docker compose down && docker compose build && docker compose up -d"

          
    
